src/main/resources/META-INF/csrfguard-ibm.properties
src/main/resources/META-INF/csrfguard.properties

https://jira.jahia.org/browse/QA-13550
Temporarily switch off experimental TokenPerPage feature. 
The following are included in this PR
I have considered the following implications of my change:

QA-13550: Temporarily switch off experimental TokenPerPage feature

---

src/main/resources/META-INF/csrfguard.template.js

https://jira.jahia.org/browse/QA-13722
The following are included in this PR
I have considered the following implications of my change:

QA-13722: definition of endsWith for IE11

---

src/main/resources/META-INF/csrfguard.template.js

https://jira.jahia.org/browse/QA-13754

QA-13754 : fix script compatibility

---

pom.xml

https://jira.jahia.org/browse/QA-13754

QA-13754 : fix module signature

---

src/main/java/org/jahia/modules/jahiacsrfguard/filters/CsrfGuardJavascriptFilter.java

https://jira.jahia.org/browse/QA-13880

QA-13880 : improve the way to detect usage of the filter

---

src/main/resources/META-INF/csrfguard-jahia.properties

https://jira.jahia.org/browse/QA-13942
Fix copy&paste error in property key

QA-13942: Fix copy&paste error

---

src/main/java/org/jahia/modules/jahiacsrfguard/config/overlay/ConfigurationOverlay.java
src/main/java/org/jahia/modules/jahiacsrfguard/config/overlay/ConfigurationOverlayProvider.java
src/main/resources/META-INF/csrfguard-jahia.properties

https://jira.jahia.org/browse/QA-13942
Fix two NPE on startup (seen in automated migration script).

QA-13942 Fix two NPE on startup

---

.circleci/config.yml

https://jira.jahia.org/browse/QA-13942
Fix missing publish step in CircleCI

QA-13942: Fix missing publish in circleci

---

src/main/resources/META-INF/csrfguard-3.1.0.properties
src/main/resources/META-INF/csrfguard-jahia.properties

https://jira.jahia.org/browse/QA-13496
Remove CSRF token from error page
- also remove space from injectIntoAttributes value in config

QA-13496: Remove CSRF token from error page

---

src/main/resources/META-INF/csrfguard-jahia.properties
src/main/resources/META-INF/csrfguard.template.js
src/main/resources/Owasp.CsrfGuard.properties

https://jira.jahia.org/browse/BACKLOG-16669
Deactivate TokenPerPage and remove debug statements.
Also take minor fixes from the csrfguard master branch.

BACKLOG-16669: Deactivate TokenPerPage and remove debug statements

---

pom.xml
src/main/resources/Owasp.CsrfGuard.properties

https://jira.jahia.org/browse/BACKLOG-16883
Upgrade csrfguard to 4.1.4-SNAPSHOT

BACKLOG-16883: Upgrade csrfguard to 4.1.4-SNAPSHOT

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-17167
Upgrade to csrfguard 4.1.4

BACKLOG-17167: Upgrade to csrfguard 4.1.4

---

pom.xml
src/main/java/org/jahia/modules/jahiacsrfguard/filters/CsrfGuardServletFilterWrapper.java
src/main/java/org/jahia/modules/jahiacsrfguard/filters/MultiReadHttpServletRequest.java
src/main/resources/META-INF/spring/jahia-csrf-guard.xml

https://jira.jahia.org/browse/QA-14215
Add support for multipart requests
The following are included in this PR
I have considered the following implications of my change:

QA-14215: Add support for multipart requests

---

src/main/java/org/jahia/modules/jahiacsrfguard/filters/CsrfGuardJavascriptFilter.java

Signed-off-by: Florent BOURASSE <fbourasse@jahia.com>
https://jira.jahia.org/browse/QA-14428
The following are included in this PR
I have considered the following implications of my change:

QA-14428: removal of incorrect content-length

---

.github/maven.settings.xml

https://jira.jahia.org/browse/BACKLOG-19985

BACKLOG-19985 - Add missing maven server

---

.github/workflows/milestone.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/on-rollback.yml

https://jira.jahia.org/browse/TECH-1081
Update deprecated steps

TECH-1081 Update deprecated steps

---

pom.xml

https://jira.jahia.org/browse/QA-14409
Update to csrfguard forked version 4.1.4-jahia1 
See https://github.com/Jahia/www-project-csrfguard/pull/1

QA-14409: Update to csrfguard forked version 4.1.4-jahia1

---

pom.xml
src/main/java/org/jahia/modules/jahiacsrfguard/filters/MultiReadHttpServletRequest.java
src/main/resources/META-INF/configurations/org.owasp.csrfguard.cfg
src/main/resources/META-INF/patches/graphql/01-tokenPerPage.started.graphql

https://jira.jahia.org/browse/BACKLOG-20895

BACKLOG-20895: Activate tokenPerPage by default

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/schedule-sonar.yml
pom.xml
src/main/resources/META-INF/csrfguard.template.uncompressed.js

https://jira.jahia.org/browse/BACKLOG-21818
Filter only urls ending with /*  (/* inside the url should be ok)

BACKLOG-21818: Filter only urls ending with /*

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-21978
Matching minimum compatibility with 8.1.6 but bumping to 4.0 to include in 8.2

BACKLOG-21978: Bump version to 4.0.0 and downgrade parent to 8.1.6.0

---

src/main/resources/META-INF/configurations/org.owasp.csrfguard.cfg
src/main/resources/META-INF/csrfguard-jahia.properties
src/main/resources/META-INF/patches/graphql/01-tokenPerPage.started.graphql

…
https://jira.jahia.org/browse/BACKLOG-20895

BACKLOG-20895: Revert changes in OSGi configuration and toggle token per page in csrfguard-jahia.properties

---

.github/maven.settings.xml

Fix missing server reference in CI maven.settings.xml

ci: update maven distribution repository name

---

.github/workflows/push-docs.yml
docs/README.md

This is just a first version of the workflow with a placeholder doc, the reste of the edits will come in a separate PR.

docs: first version of the workflow to publish documentation

---

.github/workflows/push-docs.yml
docs/README.md

Converted the Academy page to markdown during review of the content.

docs: prepared documentation for the Academy
